### ISSUE TITLE
Remove and untrack .DS_Store files

### ISSUE THREAD

**Issue by impredicative** [ranery/Bayesian-CycleGAN#1]
`.DS_Store` files should almost never be in a git repo! Please refer to the following resources to remove and untrack them from the repo:

https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

https://stackoverflow.com/questions/27317994/how-do-i-ignore-ds-store-in-my-untracked-files

**Comment by ranery** [comment]
Thank you for reminding, I have removed this file.

**Comment by impredicative** [comment]
It's still there in the evaluation directory. I don't see any entry for it in rhe .gitignore file either. Do you have someone in your team who is more experienced and can help you with it?

**Comment by wondervictor** [comment]
@impredicative  Sorry for that, I've removed all `.DS_Store` files which were created automatically in macOS and will be ignored by git through `.gitignore`. If this kind of file still exists in your local, pulling from the master branch will remove it.  :)
