### ISSUE TITLE
Add link to paper

### ISSUE THREAD

**Issue by impredicative** [ranery/Bayesian-CycleGAN#2]
I don't see a link to your Arxiv paper in the readme. Can you please add a clearly visible hyperlink to it? For reference, the link I have is https://arxiv.org/abs/1811.07465

**Comment by ranery** [comment]
Thank you for reminding, I have added arXiv link to this repo.

**Comment by impredicative** [comment]
Where is the link?

**Comment by impredicative** [comment]
This is the most incompetent response I have seen in a while. You closed the issue without fixing anything. Please have your work examined.

**Comment by ranery** [comment]
In the description part.
![image](https://user-images.githubusercontent.com/18202368/50272377-8bd0a380-0472-11e9-80d7-023d2d020bc6.png)

**Comment by wondervictor** [comment]
@impredicative README has been updated with a link to the arXiv preprint.
