### ISSUE TITLE
can't find train_bayes_z.py

### ISSUE THREAD

**Issue by LongChenCV** [ranery/Bayesian-CycleGAN#3]
Thanks for your code, valuable work.  I can't find train_bayes_z.py, could you share it? Besides what's the difference between train_bayes_z.py and train_bayes.py?

**Comment by ranery** [comment]
You can change the 11th line in train_bayes.py from "models.CycleGAN_bayes" to "models.CycleGAN_bayes_z", in which way the training script will invoke bayes_z model. The difference lies between whether the encoder network is used or not. The bayes_z model just concatenates input and latent variables z while the bayes model links input to E(x/y), that can be seen as latent f_x/y. Detail explanation can be found in arXiv paper. Thank you for your interest in this work.

**Comment by LongChenCV** [comment]
Thanks very much!
